date: "20180413"
start_time: "09:02"
end_time: "09:17"
search_terms: 
  - "reconnect"
  - "whoami"
  - "nc -s"
  - "shell"
  - "./deploy/archive/drakon.freebsd.x64_53.158.101.118"
  - "pEja72mA"
  - "./deploy/archive/libdrakon.freebsd.x64.so_198.115.236.119"
  - "eWq10bVcx"
  - "elevate"
  - "20691"
  - "/usr/sbin/sshd"
  - "inject"
  - "crash"
  - "25.159.96.207"
  - "128.55.12.73"
  - "128.55.12.167"
  - "76.56.184.25"
  - "155.162.39.48"
  - "98.115.236.119"
  - "53.158.101.118"
  - "memhelp.so"
  - "eraseme"
  - "done.so"
  - "78.205.235.65"
  - "nginx"
  - "sshd"
  - "/etc/group"
  - "/etc/passwd"
  - "/dec/gtx_dsa_675"

