date: "20180411"
start_time: "15:06"
end_time: "15:17"
search_terms: 
  - "/tmp/grain"
  - "/etc/group"
  - "sshd"
  - "nignx" 
  - "25.159.96.207"
  - "76.56.184.25"
  - "155.162.39.48"
  - "198.115.236.119"
  - "128.55.12.167"
  - "loaderDrakon"
  - "shellcode_server"
  - "libdrakon"
  - "./deploy/archive/libdrakon.freebsd.x64.so_198.115.236.119"
  - "vUGefai"
