date: "20180412"
start_time: "13:36"
end_time: "13:36"
search_terms: 
  - "145.199.103.57"
  - "128.55.12.167"
  - "104.228.117.212"
  - "128.55.12.167"
  - "webserver 1"
  - "webserver 2"
  - "allstate"
  - "drakon"
  - "browser extenstion"
  - "firefox"