date: "20180410"
start_time: "09:46"
end_time: "11:10"
search_terms: 
  - "allstate"
  - "firefox"
  - "2.233.33.53"
  - "drakon"
  - "./deploy/archive/libdrakon.linux.x64.so_5.214.163.155"
  - "libdrakon.linux.x64.so_5.214.163.155"
  - "/var/log/xtmp"
  - "145.199.103.57"
  - "128.55.12.167"
  - "61.130.69.232"
  - "2.233.33.52"
  - "180.156.107.146"
  - "5.214.163.155"
  - "webserver"
  - "shellcode_server"
  - "loaderDrakon.linux.x64"
  - "drakon.linux.x64"
  - "libdrakon.linux.x64.so"
  - "./deploy/archive/drakon.linux.x64_180.156.107.146"
  - "drakon.linux.x64_180.156.107.146"
  - "/home/admin/cache"
  - "xtmp"
  - "./deploy/archive/libdrakon.linux.x64.so_5.214.163.155"
  - "/etc/passwd"
  - "/dev"
  - "/proc"
  - "/home/admin/cache"


